import Link from "next/link";
import { Nav } from "@/components/Nav";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Beyond the Screen | Lincoln Mitchell",
  description: "Agentic design systems break the UI boundary. The same tokens, context files, and design decisions that build your product can build everything else — brand, marketing, social, print, presentations, TV, VR/AR.",
};

const channels = [
  {
    name: "Applications & Websites",
    description: "The original domain — but now the UI isn&apos;t hand-built, it&apos;s generated. Components, pages, entire apps assembled by agents that read the same tokens and context files. The design system doesn&apos;t just document the UI, it produces it.",
    color: "text-[var(--color-primary)]",
    border: "border-l-[var(--color-primary)]",
  },
  {
    name: "Prototypes & Exploration",
    description: "NorthStar prototypes, proof-of-concepts, speculative designs. The fastest way to explore a new direction is to let an agent build it from the existing system. Ten variations in an hour, all on-brand, all disposable.",
    color: "text-[var(--color-warm)]",
    border: "border-l-[var(--color-warm)]",
  },
  {
    name: "Email & Notifications",
    description: "Transactional emails, newsletters, push notifications. The brand voice and visual identity flow into every customer touchpoint — not just the product surface.",
    color: "text-[var(--color-accent)]",
    border: "border-l-[var(--color-accent)]",
  },
  {
    name: "Documentation & Help",
    description: "Product docs, onboarding guides, knowledge bases. Consistently branded, correctly voiced, structured from the same design decisions. Documentation stops being the thing nobody styles.",
    color: "text-[var(--color-secondary)]",
    border: "border-l-[var(--color-secondary)]",
  },
  {
    name: "Brand Guidelines",
    description: "Token values, colour rationale, typography hierarchy — generated directly from the system rather than maintained as a parallel document that drifts from code.",
    color: "text-[var(--color-primary)]",
    border: "border-l-[var(--color-primary)]",
  },
  {
    name: "Marketing Collateral",
    description: "Social cards, email templates, campaign banners. The brand constraints are already in the tokens. The agent reads them. The output is always on-brand, without a briefing.",
    color: "text-[var(--color-accent)]",
    border: "border-l-[var(--color-accent)]",
  },
  {
    name: "Social Media",
    description: "Correctly branded posts, sized for each platform, in the right voice. The design system carries the voice layer — not just colour and type, but tone, message hierarchy, the editorial stance.",
    color: "text-[var(--color-secondary)]",
    border: "border-l-[var(--color-secondary)]",
  },
  {
    name: "Print & Packaging",
    description: "Brochures, business cards, signage. The same spacing philosophy, the same typographic scale. Print becomes a downstream output of the same source, not a separate project.",
    color: "text-[var(--color-warm)]",
    border: "border-l-[var(--color-warm)]",
  },
  {
    name: "Presentations",
    description: "Slide decks in brand, automatically. Not a template the team ignores — a generator that produces compliant slides from structured content, every time.",
    color: "text-[var(--color-primary)]",
    border: "border-l-[var(--color-primary)]",
  },
  {
    name: "TV / Audio-Visual",
    description: "Motion design briefs, storyboards, ad frameworks — all generated with brand compliance baked in. The design system describes the brand at a level of abstraction that works for any medium.",
    color: "text-[var(--color-accent)]",
    border: "border-l-[var(--color-accent)]",
  },
  {
    name: "VR / AR",
    description: "Spatial design from the same primitives. Colour tokens don&apos;t care whether they&apos;re applied to a web component or a volumetric surface. The system travels.",
    color: "text-[var(--color-secondary)]",
    border: "border-l-[var(--color-secondary)]",
  },
];

const proofPoints = [
  {
    output: "Portfolio website",
    source: "CLAUDE.md + design tokens + component system",
    note: "Every page generated by agents consuming the same system",
  },
  {
    output: "CV / Resume",
    source: "CLAUDE.md career narrative + token-derived styling",
    note: "Brand-consistent document, not a separate design artefact",
  },
  {
    output: "LinkedIn posts",
    source: "CLAUDE.md voice + INC framework context",
    note: "Same brand voice, same positioning, different medium",
  },
  {
    output: "Conference abstract",
    source: "CLAUDE.md methodology + IDS 2026 context",
    note: "Consistent thought leadership, generated not drafted",
  },
];

export default function BeyondUI() {
  return (
    <>
      <Nav />

      {/* Hero */}
        <header className="flex flex-col items-center text-center px-8 md:px-20 pt-30 pb-20 gap-6 max-w-[1440px] mx-auto">
          <span className="font-mono text-xs font-medium text-[var(--color-warm)] tracking-[0.2em] uppercase">Agentic Expansion</span>
          <h1 className="font-display text-[clamp(2.5rem,6vw,4.5rem)] font-bold text-white tracking-[-0.03em] leading-[1]">
            Beyond the <span className="text-[var(--color-warm-light)]">Screen</span>
          </h1>
          <p className="text-xl text-white/50 max-w-[640px] leading-relaxed">
            Agentic design systems break the UI boundary. The same tokens, the same context files, the same system that builds your product — can build everything else. Brand, marketing, social, print, presentations, TV, VR/AR. The screen is just one channel.
          </p>
          <p className="font-mono text-xs text-[#475569] tracking-wider uppercase">IDS 2026 · WhatsApp Track</p>
        </header>

        <main>
          {/* The Problem */}
          <section className="bg-[#0f172a] px-8 md:px-20 py-24 max-w-[1440px] mx-auto">
            <span className="font-mono text-xs font-medium text-[var(--color-warm)] tracking-[0.2em] uppercase block mb-4">The Problem</span>
            <h2 className="font-display text-[clamp(2rem,4vw,2.5rem)] font-bold text-white tracking-tight leading-[1.1] mb-6">
              Design systems are trapped behind glass
            </h2>
            <div className="text-[17px] text-white/50 leading-relaxed max-w-[720px] space-y-6">
              <p>
                Every design systems architect I know has been asked to wear many hats. Build the component library. Also design the conference booth. Also produce the pitch deck. Also do the social graphics. Also review the print spec for the brochure.
              </p>
              <p>
                The design system helps with none of that. It lives in Figma and in code, it serves the product team, and it stops at the edge of the UI. Everything else is handled with whatever tool is closest to hand, by whoever has capacity, with whatever brand consistency they can manage.
              </p>
              <p>
                This isn&apos;t a workflow problem. It&apos;s an architectural one. Traditional design systems are built to serve UI, and UI only. They&apos;re not structured to be consumed by anything outside a component renderer. The brand knowledge is in there — but it&apos;s locked in.
              </p>
              <p className="text-[var(--color-warm-light)]">
                Agentic design systems change the lock. Not by adding features. By changing what the system <em>is</em>.
              </p>
            </div>
          </section>

          {/* The Channels */}
          <section className="px-8 md:px-20 py-24 max-w-[1440px] mx-auto">
            <span className="font-mono text-xs font-medium text-[var(--color-primary)] tracking-[0.2em] uppercase block mb-4">The Channels</span>
            <h2 className="font-display text-[clamp(2rem,4vw,2.5rem)] font-bold text-white tracking-tight leading-[1.1] mb-4">
              Every surface, one source
            </h2>
            <p className="text-[17px] text-white/50 leading-relaxed max-w-[640px] mb-12">
              When a design system is machine-readable, every AI agent that can consume it becomes a delivery channel. The same brand constraints apply everywhere — not because someone enforced them, but because they&apos;re structural.
            </p>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {channels.map((ch) => (
                <div key={ch.name} className={`p-8 bg-[#0a0f1a] border border-[#1e293b] border-l-[3px] ${ch.border} rounded-xl`}>
                  <h3 className={`font-display text-xl font-semibold mb-3 ${ch.color}`}>{ch.name}</h3>
                  <p className="text-sm text-white/40 leading-relaxed" dangerouslySetInnerHTML={{ __html: ch.description }} />
                </div>
              ))}
            </div>
          </section>

          {/* The Mechanism */}
          <section className="bg-[#0f172a] px-8 md:px-20 py-24 max-w-[1440px] mx-auto">
            <span className="font-mono text-xs font-medium text-[var(--color-secondary)] tracking-[0.2em] uppercase block mb-4">The Mechanism</span>
            <h2 className="font-display text-[clamp(2rem,4vw,2.5rem)] font-bold text-white tracking-tight leading-[1.1] mb-6">
              Tokens + context + agents = any output format
            </h2>
            <div className="text-[17px] text-white/50 leading-relaxed max-w-[720px] space-y-6">
              <p>
                The mechanism is straightforward once you see it. An agentic design system has three layers that traditional design systems lack:
              </p>
            </div>

            <div className="mt-10 max-w-[720px] flex flex-col gap-5">
              <div className="p-7 bg-[#0a0f1a] border border-[#1e293b] border-l-[3px] border-l-[var(--color-primary)] rounded-xl">
                <h3 className="font-display text-lg font-semibold text-[var(--color-primary)] mb-2">Tokens are format-agnostic</h3>
                <p className="text-[15px] text-white/40 leading-relaxed">
                  A colour token is just a value and a semantic name. It doesn&apos;t know whether it&apos;s being applied to a React component, a print layout, or a motion design brief. Once you structure tokens as JSON or CSS custom properties, any agent can read them.
                </p>
              </div>

              <div className="p-7 bg-[#0a0f1a] border border-[#1e293b] border-l-[3px] border-l-[var(--color-secondary)] rounded-xl">
                <h3 className="font-display text-lg font-semibold text-[var(--color-secondary)] mb-2">Context files carry the brand layer</h3>
                <p className="text-[15px] text-white/40 leading-relaxed">
                  This is the <strong className="text-white">&#60;N&#62;</strong> in I&#60;N&#62;C — the Narrate layer. Not just colour values and spacing scales, but brand voice, visual principles, spacing philosophy, editorial stance, target audience, use cases. CLAUDE.md isn&apos;t a coding instruction file. It&apos;s a brand constitution that AI agents can consume directly.
                </p>
              </div>

              <div className="p-7 bg-[#0a0f1a] border border-[#1e293b] border-l-[3px] border-l-[var(--color-accent)] rounded-xl">
                <h3 className="font-display text-lg font-semibold text-[var(--color-accent)] mb-2">Agents route to the right output format</h3>
                <p className="text-[15px] text-white/40 leading-relaxed">
                  You don&apos;t need one agent for everything. You need a design system structured so that any agent — the one writing React, the one generating social copy, the one producing a print brief — is working from the same source of truth. The routing is trivial once the system is machine-readable.
                </p>
              </div>
            </div>
          </section>

          {/* The Proof */}
          <section className="px-8 md:px-20 py-24 max-w-[1440px] mx-auto">
            <span className="font-mono text-xs font-medium text-[var(--color-accent)] tracking-[0.2em] uppercase block mb-4">The Proof</span>
            <h2 className="font-display text-[clamp(2rem,4vw,2.5rem)] font-bold text-white tracking-tight leading-[1.1] mb-4">
              My portfolio already does this
            </h2>
            <p className="text-[17px] text-white/50 leading-relaxed max-w-[640px] mb-12">
              This isn&apos;t theoretical. The site you&apos;re reading right now demonstrates the principle. One design system, one CLAUDE.md, multiple outputs — all consistent, all generated, none manually styled.
            </p>

            <div className="max-w-[800px] flex flex-col gap-4">
              {proofPoints.map((item) => (
                <div key={item.output} className="flex gap-6 items-start p-6 bg-[#0a0f1a] border border-[#1e293b] rounded-xl">
                  <div className="shrink-0 pt-0.5">
                    <div className="w-2 h-2 rounded-full bg-[var(--color-warm)]" />
                  </div>
                  <div className="flex-1">
                    <div className="flex flex-wrap gap-3 items-baseline mb-2">
                      <span className="font-display text-base font-semibold text-white">{item.output}</span>
                      <span className="font-mono text-[11px] text-[var(--color-accent)] bg-[var(--color-accent)]/10 px-2 py-0.5 rounded">from {item.source}</span>
                    </div>
                    <p className="text-sm text-white/40 leading-relaxed">{item.note}</p>
                  </div>
                </div>
              ))}
            </div>

            <p className="text-[17px] text-white/50 leading-relaxed max-w-[720px] mt-10">
              None of these outputs share a stylesheet or a template. They share a <em>system</em>. The consistency isn&apos;t maintained — it&apos;s structural.
            </p>
          </section>

          {/* The Shift */}
          <section className="bg-[#0f172a] px-8 md:px-20 py-24 max-w-[1440px] mx-auto">
            <span className="font-mono text-xs font-medium text-[var(--color-warm)] tracking-[0.2em] uppercase block mb-4">The Shift</span>
            <h2 className="font-display text-[clamp(2rem,4vw,2.5rem)] font-bold text-white tracking-tight leading-[1.1] mb-6">
              Wearing many hats is a superpower, not a burden
            </h2>
            <div className="text-[17px] text-white/50 leading-relaxed max-w-[720px] space-y-6">
              <p>
                The traditional framing: &ldquo;design system team&rdquo; — a group of specialists maintaining the product design infrastructure. It serves the product. It doesn&apos;t touch anything else. Everyone else builds their own brand collateral their own way.
              </p>
              <p>
                The agentic framing: &ldquo;design system as creative department&rdquo;. The system doesn&apos;t serve one team. It serves every team that touches the brand. Marketing, communications, engineering, sales — they all consume from the same source. The design system architect becomes the keeper of the brand constitution, not just the component library.
              </p>
              <p>
                I&apos;ve been asked to wear many hats throughout my career. Build the product design system. Also the brand guidelines. Also the conference materials. Also the pitch decks. The traditional response is to treat this as scope creep. The agentic response is to build a system that makes every hat easy to wear.
              </p>
              <p>
                One person with an agentic design system isn&apos;t one person doing the work of many. They&apos;re one person <em>orchestrating</em> the work of many — and the system maintains the brand integrity across all of it without anyone needing to check.
              </p>
              <p className="text-[var(--color-warm-light)]">
                This is what I mean by the INC framework as an amplifier. It doesn&apos;t change what I can think. It changes what I can ship.
              </p>
            </div>
          </section>

          {/* Quote */}
          <section className="px-8 md:px-20 py-20 text-center max-w-[1440px] mx-auto">
            <blockquote className="relative font-display text-[clamp(1.5rem,3vw,2rem)] font-medium text-white leading-[1.4] tracking-tight max-w-[900px] mx-auto mb-6">
              <span className="absolute -top-12 -left-6 text-[120px] text-[var(--color-warm)]/30 font-serif leading-none">&ldquo;</span>
              The design system isn&apos;t the component library. It&apos;s the brand constitution. Once it&apos;s machine-readable, every channel becomes a downstream output.
            </blockquote>
            <cite className="text-sm text-[#64748b] not-italic">Beyond the Screen — the agentic expansion thesis</cite>
          </section>

          {/* CTA */}
          <section className="px-8 md:px-20 py-24 max-w-[1440px] mx-auto text-center">
            <h2 className="font-display text-[clamp(2rem,4vw,2.5rem)] font-bold text-white tracking-tight mb-4">
              Ready to make your design system a creative department?
            </h2>
            <p className="text-lg text-white/50 max-w-[560px] mx-auto mb-8 leading-relaxed">
              If you&apos;re building a design system that only serves your product UI, you&apos;re leaving most of its potential on the table. Let&apos;s talk about what the agentic expansion looks like for your brand.
            </p>
            <div className="flex gap-4 justify-center flex-wrap">
              <a href="https://cal.com/lincmitch" target="_blank" rel="noopener noreferrer" className="text-[15px] font-medium text-white bg-[var(--color-primary)] px-8 py-3.5 rounded-lg no-underline hover:bg-[var(--color-primary-dark)] transition-colors">
                Book a Conversation
              </a>
              <Link href="/thoughts/competing-values" className="text-[15px] font-medium text-white/50 border border-[#1e293b] px-8 py-3.5 rounded-lg no-underline hover:text-white hover:border-[#475569] transition-colors">
                Competing Values →
              </Link>
            </div>
          </section>
        </main>

        <footer className="max-w-[1440px] mx-auto px-8 py-10 border-t border-[#1e293b] text-center">
          <p className="text-[13px] text-[#475569] mb-2">This page was generated via Claude Code prompts — synthesising an IDS 2026 WhatsApp track insight with sixteen years of wearing many hats.</p>
          <p className="text-[13px] text-[#475569]"><Link href="/" className="text-blue-400 no-underline">lincolnmitchell.io</Link> &middot; Interfaces-N-Creatives since 2008</p>
        </footer>
    </>
  );
}
